### ISSUE TITLE
Download and Install Instructions should mention making install.sh executable

### ISSUE THREAD

**Issue by scotty3785** [piborg/zeroborg#1]
The README.md file instructions tell the user to clone the git repository and then run ./install.sh.

This step does not work as install.sh is not executable.

Suggest that a step is added telling the user to run 
`chmod +x install.sh`

**Comment by piborg** [comment]
Well spotted :)

I have added a `chmod` line as suggested.
I have also added an `apt-get` for git since it may not be installed already.
